#!/usr/bin/env python3
"""Build dist/usg-meter-sizing.js from src/js/meter_sizing.js.

The only thing this does is substitute the capacity tables and a version
stamp into the template, so the numbers live in exactly one place
(data/capacities.json) and cannot drift between the Python and the browser.

    python tools/build.py            # write the bundle
    python tools/build.py --check    # exit 1 if the committed bundle is stale

CI runs --check, which is what stops a rules change from shipping to the
website without the rebuilt bundle beside it.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEMPLATE = REPO / "src" / "js" / "meter_sizing.js"
DATA = REPO / "data" / "capacities.json"
OUT = REPO / "dist" / "usg-meter-sizing.js"


def version(template, payload):
    """A short hash of the inputs this bundle was built from.

    NOT the git commit. It used to be `git rev-parse --short HEAD`, which made
    the build non-deterministic: CI rebuilds at a different commit than the one
    the committed bundle was built at, so the two never matched and `--check`
    failed on every single push. Worse, it failed for a reason that had nothing
    to do with the rules.

    Hashing the sources instead means identical sources always produce an
    identical bundle, anywhere. `--check` then tests what it is supposed to -
    whether dist/ was rebuilt after the rules changed - and the stamp still
    identifies a build, because you can recompute it from the sources and
    compare it to what the live page reports.
    """
    h = hashlib.sha256()
    h.update(template.encode("utf-8"))
    h.update(payload.encode("utf-8"))
    return h.hexdigest()[:12]


def render():
    template = TEMPLATE.read_text()
    data = json.loads(DATA.read_text())

    if "/*__CAPACITIES__*/ null" not in template:
        raise SystemExit("template is missing the /*__CAPACITIES__*/ placeholder")
    if '/*__VERSION__*/ "dev"' not in template:
        raise SystemExit("template is missing the /*__VERSION__*/ placeholder")

    # separators without spaces keeps the bundle small; the tables are the
    # bulk of the file.
    payload = json.dumps(data, separators=(",", ":"))
    js = template.replace("/*__CAPACITIES__*/ null", payload)
    js = js.replace('/*__VERSION__*/ "dev"', json.dumps(version(template, payload)))
    return (
        "/* Generated by tools/build.py from src/js/meter_sizing.js and\n"
        "   data/capacities.json. Do not edit. */\n" + js
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed bundle matches the sources")
    args = ap.parse_args()

    js = render()

    if args.check:
        if not OUT.exists():
            print(f"FAIL {OUT} does not exist. Run: python tools/build.py")
            return 1
        if OUT.read_text() != js:
            print(f"FAIL {OUT} is stale. Run: python tools/build.py and commit it.")
            return 1
        print(f"OK   {OUT.relative_to(REPO)} is up to date")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js)
    print(f"wrote {OUT.relative_to(REPO)}  ({len(js):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
